version: '3.3'
services:
  db:
    container_name: custom_form_demo_db
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: "development"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    expose:
      - 3306
  app:
    container_name: custom_form_demo_app
    build: .
    command: >
      /bin/sh -c
        "rm -f tmp/pids/server.pid &&
        bin/rails s -p 3030 -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle:/rails/vendor/bundle
    expose:
      - 3030
    ports:
      - 3030:3030
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql:
  bundle:
    driver: local
